# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Docker Client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Docker Client
  pod 'Alamofire'
  pod 'SwiftyJSON'  
  pod 'JGProgressHUD'
  target 'Docker ClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Docker ClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
